# Configure CrystalHello below.
require-item: true
required-item: ice
amount-required: 1 #the absolute value of the items that will be used up upon command.
successful-message: CrystalCraftMC has decided to grant the wish trapped deepest in your heart: Hello, #Player's name will be added here inside the code + "!"
failed-message: You are holding the wrong key. Please try again, and may the odds be ever in your favor!
lacking-quantity: You have the right key, but your key is not strong enough yet. Try adding to its strength.
successful-color: Aqua #Use bukkit approved color names only
failed-color: Red #Use bukkit approved color names only
