name: CrystalHello
main: com.crystalcraftmc.crystalhello.CrystalHello
version: 1.0.1
description: Have the server say hello when you type the command and hold an item!
authors: [jflory7, Jacc734]
website: http://crystalcraftmc.com

commands:
  crystal:
    description: See if the server feels like saying hello!
    aliases: [ccmc, crystalcraftmc]
    permission: crystalhello.greetings

permissions:
  crystalhello.greetings:
    description: See if the server feels like saying hello!
    default: true